---
# tasks file for nginx
#

- include: install.yaml
  tags: [ never, install_nginx ]

- include: start.yaml
  tags: [ never, start_nginx ]

- include: stop.yaml
  tags: [ never, stop_nginx ]

- include: uninstall.yaml
  tags: [ never, uninstall_nginx ]
