---
- name: install tools for RedHat Family
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
#  notify: "Install {{ item }}"
  loop: "{{ list_to_install }}"
  when: ansible_os_family == 'RedHat'

- name: install tools for Debian Family
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
#  notify: "Install {{ item }}"
  loop: "{{ list_to_install }}"
  when: ansible_os_family == 'Debian'

